import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="it">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex min-h-screen">
            {/* Sidebar fissa solo su desktop */}
            <div className="hidden lg:block w-96 fixed left-0 top-0 h-full z-40">
              <Sidebar alwaysVisible />
            </div>

            {/* Contenuto principale */}
            <div className="flex-1 lg:ml-96">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
